### ISSUE TITLE
Remove blank fields / replace with some encouraging placeholders on no selection

### ISSUE THREAD

**Issue by kubukoz** [MateuszKubuszok/ScalaTree#2]
![image](https://user-images.githubusercontent.com/894884/111537289-8a82a400-876b-11eb-9728-aaba4861f0cd.png)

**Comment by MateuszKubuszok** [comment]
I hide these fields when no topic is selected. Sources list might be empty though.

**Comment by MateuszKubuszok** [comment]
Added placeholders for empty values.
